### PR TITLE
updated Thermostat and Homecoach

### PR DESCRIPTION
**Pull request by JurgenLB**
This is to restore the old behavior for the Thermostat.
Now the code search for a ID or Name for the Relaystation and than for the Thermostat module.

The valves are not accessible by the class Thermostat

### CODE REVIEW

**Comment by JurgenLB** [comment]
I have also changed HomeData.
This works for me with Self-test and a Test-script I have.
If you want me to change something, let me know

**Comment by JurgenLB** [comment]
This will fix and close #88
I believe.

The thermostat is the Module and the Relay is the Bridge for the Thermostat and Valves are also Modules,
but the valves are not accessible by the Thermostat class, they are in HomesData/HomeStatus.

I think Netatmo is going to put all devices in HomesData/HomeStatus.

**Comment by philippelt** [comment]
Hello @JurgenLB ,

could you explain the following code:  
```python
if device.get('time_utc',limit+10) > limit :
    return {'When': ds, '_id': hid, }
else:
    return {'When': 0, 'id': hid}
```

In the else clause, the '_id' property has become 'id'. Is it a typo ?
In this case, you could simplify your code with
```python
return { '_id': hid, 'When': ds if device.get('time_utc',limit+10) > limit else 0}
```

**Comment by JurgenLB** [comment]
yes your correct, its a typo from me.
I will change this.

**Comment by philippelt** [comment]
Hello Jurgen,

you have done a very great job of refactoring.

I don't understand the benefit of saving the access_token considering that it will be discarded before any use (with expiration still forced) ?

**Comment by JurgenLB** [comment]
When we generate a token in the portal from Netatmo.
We get a access_token and a refresh_token, now we only use the refresh_token to get a new access_token.
I was thinking is it not beter to use the generated access_token and only if that fails use the refresh_token.

So its only on the first run that the access_token is imported, after that it can be stored or only the key remains
also the access_token is short living so its important to use it quick after generating.
I do see that when I run this library with a correct refresh_token after 1u. the login gives error message for not correct anymore.
This is the reason I was looking to the authentication.
I think the refresh_token is longer than 1u. but the access_token can be expired after 1u. 

kind regards

Jurgen

**Comment by JurgenLB** [comment]
maybe it is better to undo the changes off the Token and save that for an other time.

**Comment by philippelt** [comment]
I agree with you, until Netatmo allow longer lived access token, it is not necessary to save it in the credential file considering it will probably immediately be discarded on new authentication.

**Pull request merged**
