### PR TITLE
Add support for Netatmo Welcome camera

### PR DESCRIPTION
**Pull request by jabesq**
I update your python API for netatmo in order to be aligned with the updated Netatmo's API (some function has been deprecated) and also to add the support for the Welcome Camera.

### CODE REVIEW

**Comment by philippelt** [comment]
Many thanks to you, you have done a really great job.

Therefore, I consider critical to provide appropriate documentation, I know this takes time and is somehow boring, because many users of the library are not professional developers and hugely rely on examples and documentation.

Please update the documentation with the change to the base features and provide some for the camera functions you did implement.

You should also update the examples to ensure they work with updated module and use the appropriates (not deprecated) classes.

I will then be able to merge your contribution.

Thanks in advance for your efforts and your comprehension !
And congratulations for being an open source contributor.

**Comment by jabesq** [comment]
Should I add more documentation or is it ok to you?
I updated the version to 0.5.0 because the project that will use your lib (home-assistant) was using another fork which was labelled as 0.4.0 so I wanted to avoid conflicts

**Comment by philippelt** [comment]
Sorry for the delay, I have currently low availability for interesting tasks :-)

Thanks for the changes but I haven't seen usage.md (single documentation page, the most important documentation) and ensure to submit a new pull request with all updated files.

**Comment by philippelt** [comment]
Great job, thanks Hugo

**Pull request merged**
